"""binary features

Revision ID: 1cf56fadd556
Revises: ded957c74c6c
Create Date: 2021-10-31 11:53:29.761404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1cf56fadd556"
down_revision = "ded957c74c6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tracking", "estimation", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tracking", "estimation", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
