"""mental balanc tags

Revision ID: 4aa4bc5a49c2
Revises: 1cf56fadd556
Create Date: 2022-01-04 12:03:57.141052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from trackme.tracking.types.tracking import MentalBalanceTagEnum as mbe


# revision identifiers, used by Alembic.
revision = "4aa4bc5a49c2"
down_revision = "1cf56fadd556"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    mentalbalancetagenum = postgresql.ENUM(
        mbe.chores.value, mbe.social.value, mbe.fun.value, mbe.mastery.value, name="mentalbalancetagenum"
    )
    mentalbalancetagenum.create(op.get_bind())
    op.add_column("tracking", sa.Column("balance_tag", mentalbalancetagenum, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracking", "balance_tag")
    op.execute("DROP TYPE mentalbalancetagenum;")
    # ### end Alembic commands ###
