"""add topic and attribute

Revision ID: 637cd44b745f
Revises: de7bab7ec5ac
Create Date: 2021-04-04 21:00:31.828808

"""
from alembic import op
import sqlalchemy as sa
from trackme.tracking.models.seeder import set_topics

# revision identifiers, used by Alembic.
revision = '637cd44b745f'
down_revision = 'de7bab7ec5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    set_topics(op)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attributes')
    op.drop_table('topics')
    # ### end Alembic commands ###
