"""attributes constraint and icons

Revision ID: 72758d0c5410
Revises: e3e8aae9d6f6
Create Date: 2021-10-03 13:23:52.777036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "72758d0c5410"
down_revision = "e3e8aae9d6f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attributes", sa.Column("icon_name", sa.String(), nullable=True))
    op.create_unique_constraint(
        "unique_attribute", "attributes", ["user_id", "topic_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_attribute", "attributes", type_="unique")
    op.drop_column("attributes", "icon_name")
    # ### end Alembic commands ###
