"""change attribute user behaviour

Revision ID: b6fc51b5d4ab
Revises: d4f3409c749d
Create Date: 2021-04-05 15:13:50.322549

"""
from alembic import op
import sqlalchemy as sa
from trackme.tracking.models.seeder import set_default_attributes

# revision identifiers, used by Alembic.
revision = 'b6fc51b5d4ab'
down_revision = 'd4f3409c749d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attributes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('attributes_user_id_fkey', 'attributes', 'users', ['user_id'], ['id'])

    set_default_attributes(op)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attributes_user_id_fkey', 'attributes', type_='foreignkey')
    op.drop_column('attributes', 'user_id')
    # ### end Alembic commands ###
