"""attributes visibility

Revision ID: c7a39b442939
Revises: 4aa4bc5a49c2
Create Date: 2022-02-12 22:08:52.953879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7a39b442939"
down_revision = "4aa4bc5a49c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attributes", sa.Column("active", sa.Boolean(), nullable=True))
    op.execute("UPDATE attributes SET active = true")
    op.alter_column("attributes", "active", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attributes", "active")
    # ### end Alembic commands ###
