"""add users

Revision ID: de7bab7ec5ac
Revises: 
Create Date: 2021-04-04 20:41:55.983047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "de7bab7ec5ac"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("pwhash", sa.String(length=240), nullable=False),
        sa.Column("email", sa.String(length=240), nullable=False),
        sa.Column("registration", sa.DateTime(), nullable=False),
        sa.Column("last_active", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_users_last_active"), "users", ["last_active"], unique=False
    )
    op.create_index(
        op.f("ix_users_registration"), "users", ["registration"], unique=False
    )
    op.create_table(
        "user_activity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("token", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("activation", sa.DateTime(), nullable=False),
        sa.Column("ip", sa.String(), nullable=True),
        sa.Column("client", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_activity")
    op.drop_index(op.f("ix_users_registration"), table_name="users")
    op.drop_index(op.f("ix_users_last_active"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
