"""attributes depend on users

Revision ID: ded957c74c6c
Revises: 72758d0c5410
Create Date: 2021-10-04 09:39:30.552874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ded957c74c6c"
down_revision = "72758d0c5410"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
