"""attributes to entrey manyrelationship

Revision ID: fd48e757c490
Revises: b6fc51b5d4ab
Create Date: 2021-04-06 20:51:56.183331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd48e757c490'
down_revision = 'b6fc51b5d4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes_2_entry',
    sa.Column('attribute_id', sa.Integer(), nullable=True),
    sa.Column('tracking_entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['tracking_entry_id'], ['tracking.id'], )
    )
    op.add_column('tracking', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking', 'deleted_at')
    op.drop_table('attributes_2_entry')
    # ### end Alembic commands ###
